pg_host: 10.91.27.55
pg_db:  dwh
pg_user: postgres
pg_pwd: postgres
pg_port: 5432
pg_schema: public
nz_db: DB_RESEVO
nz_user: USR_RESEVO
nz_pwd: passw0rd
nz_client_dir: C:/Program Files (x86)/IBM Netezza Tools/Bin
#nz_dsn: RESEVO
nz_driver: NetezzaSQL
nz_server: 10.91.27.99

