pg_host: <your postgres hostname or IP>
pg_db:  <your postgres database name>
pg_user: <your postgres user name>
pg_pwd: <your postgres password>
pg_port: 5432
pg_schema: public
nz_db: <your nz database name>
nz_user: <your nz user name>
nz_pwd: <your nz password>
nz_client_dir: C:/Program Files (x86)/IBM Netezza Tools/Bin

nz_driver: NetezzaSQL
nz_server: <nz IP address or hostname>

